"""refactor_auth

Revision ID: e1f5a55dd9c1
Revises: 2eed375c519c
Create Date: 2025-11-28 18:56:36.181447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f5a55dd9c1'
down_revision: Union[str, None] = '2eed375c519c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_organization_members_id'), 'organization_members', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_organization_members_user_id'), 'organization_members', ['user_id'], unique=False, schema='public')
    op.create_table('tokens',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tokens_id'), 'tokens', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tokens_token'), 'tokens', ['token'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tokens_user_id'), 'tokens', ['user_id'], unique=False, schema='public')
    op.drop_index(op.f('ix_public_users_organization_id'), table_name='users')
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.create_index(op.f('ix_public_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_public_tokens_user_id'), table_name='tokens', schema='public')
    op.drop_index(op.f('ix_public_tokens_token'), table_name='tokens', schema='public')
    op.drop_index(op.f('ix_public_tokens_id'), table_name='tokens', schema='public')
    op.drop_table('tokens', schema='public')
    op.drop_index(op.f('ix_public_organization_members_user_id'), table_name='organization_members', schema='public')
    op.drop_index(op.f('ix_public_organization_members_organization_id'), table_name='organization_members', schema='public')
    op.drop_index(op.f('ix_public_organization_members_id'), table_name='organization_members', schema='public')
    op.drop_table('organization_members', schema='public')
    # ### end Alembic commands ###
