"""fix token expires_at timezone

Revision ID: 9b59452df32a
Revises: 4ba8d763d3da
Create Date: 2025-11-29 18:20:58.229970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b59452df32a'
down_revision: Union[str, None] = '4ba8d763d3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organization_members_organization_id_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_user_id_fkey'), 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('tokens_user_id_fkey'), 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tokens_user_id_fkey'), 'tokens', 'users', ['user_id'], ['id'])
    op.alter_column('tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'organization_members', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_user_id_fkey'), 'organization_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('organization_members_organization_id_fkey'), 'organization_members', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
